### ISSUE TITLE
WhiteSource Integration for kdb-studio

### ISSUE THREAD

**Issue by mcleo-d** [finos/kdb-studio#104]
## Description

This GitHub issue is a request to the FINOS Infrastructure team to work with @alvin-c-shih and the FINOS KDB project to integrate WhiteSource on the FINOS [kdb-studio](https://github.com/finos/kdb-studio) repo. 

https://community.finos.org/docs/development-infrastructure/code-validation/whitesource

## Actions
- [ ] WhiteSource integrated into [kdb-studio](https://github.com/finos/kdb-studio) repo.
- [ ] FINOS works with KDB team on exclusions and false positive filtering.
- [ ] WhiteSource rolled out for kdb-studio.

cc @maoo @TheJuanAndOnly99 @robmoffat

**Comment by robmoffat** [comment]
Please review the above PR
