### ISSUE TITLE
there should be a key binding to close chart windows

### ISSUE THREAD

**Issue by adavies42** [finos/kdb-studio#116]
chart windows should be closable from the keyboard

i suggest ctrl+w

**Comment by gyorokpeter** [comment]
You can already close them with Alt+F4.

**Comment by adavies42** [comment]
you close editor tabs with ^W, wouldn't that be more consistent here?

**Comment by gyorokpeter** [comment]
Sure, we can add an _additional_ hotkey. Just from the title I was interpreting it as there is _no way_ to close them now, which would be surprising as all OSs that I'm aware of have a default "close window" hotkey that works without the app having to do anything.
