### ISSUE TITLE
How to update the TCP/IPC version on the app?

### ISSUE THREAD

**Issue by SidPatel-TH** [finos/kdb-studio#147]
## Support Question
I just started using this with one of the newer versions of the KX system package and I can't seem to connect to the gateway process and run into issues with IPC version mismatch. From my understanding the KX process is expecting a newer IPC version from the client, aka kdb-studio. How do I go about doing that or compile the code with newer version?

Thanks,
Sid

**Comment by gyorokpeter** [comment]
Because of limitations of the Java language itself, it is not possible to implement newer versions of the IPC protocol, as they would require arrays to have 64-bit sizes. If you have data that exceeds this size, you will have to look for alternative solutions, such as PyKX or the VSCode extension.
