### ISSUE TITLE
Allow changing font size from options dialog

### ISSUE THREAD

**Issue by gyorokpeter** [finos/kdb-studio#7]

**Comment by gyorokpeter** [comment]
We need some help on how to change the font dynamically after clicking OK in the dialog.

**Comment by mcleo-d** [comment]
Hi @gyorokpeter and @alvin-c-shih,

I have now added a `java` label to the kdb-studio **Labels** list.  

Feel free to add `java` to this item, and others items, that require Java assistance.

James.

**Comment by gyorokpeter** [comment]
@mcleo-d Thanks, we will do that in the future. For now this is actually fixed by #12 .
